project_tracker/views/project.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from flask_mongoengine.wtf import model_form
from project_tracker.models import Project, Note, User

project = Blueprint('projects', __name__, template_folder='templates')


@project.route('/', methods=['POST','GET'])
def home(): 
    projects = Project.objects(public=True)
    # projects = Project.objects.all()
    return render_template('projects/list.html', projects=projects)

@project.route('/new', methods=['POST','GET'])
@login_required
def new():
    project = Project()
    form_project = model_form(Project,  field_args = {'title': {'label': 'Title'},'description': {'label': 'Project Description'},
                                                         'primary_language': {'label':'Primary Programming Language'}, 'tools': {'label':'Other Tools'}, 'slug': {'label':'Unique Project Name'},
                                                         'repo': {'label':'GitHub Repository'}, 'location_url': {'label': 'Hosted Link'},'status': {'label':'Status'}}, 
                                                         exclude=('slug', 'startDate', 'endDate', 'createdDate', 'notes', 'closed', 'week_completed', 'minutes_worked', 'owner'))
    form = form_project(request.form)
    return render_template('projects/create.html', form=form)


@project.route('/create', methods=['POST'])
@login_required
def create():
    public = False    
    if request.form.get(public) == 'y':
        public = True
    else:
        public = False

    project = Project()
    project.title = request.form['title']
    project.public = public
    project.description = request.form['description']
    project.primary_language = request.form.get('primary_language')
    project.tools = request.form.get('tools')
    project.status = request.form['status']
    project.repo = request.form.get('repo')
    project.sources = request.form.get('sources')
   
    project.owner = current_user.id
    project.save()
    _id = project.id

    return render_template('projects/detail.html',project=project)


class DetailView(MethodView):

    form = model_form(Note, field_args={'body' :{'label': 'Write your comment here...'}}, exclude=['publishedDate', 'author'])
    @login_required
    def get_context(self, _id):
        project = Project.objects.get_or_404(id=_id)
        form = self.form(request.form)

        context = {
            "project": project,
            "form": form
        }
        return context
    @login_required
    def get(self, _id):
        context = self.get_context(_id)
        return render_template('projects/detail.html', **context)
    @login_required
    def post(self, _id):
        context = self.get_context(_id)
        form = context.get('form')

        if form.validate():
            note = Note()
            form.populate_obj(note)
            note.author = current_user.id

            project = context.get('project')
            project.notes.append(note)
            project.save()

            return redirect(url_for('projects.detail', _id=_id))
        return render_template('projects/detail.html', **context)
project.add_url_rule('/<_id>/', view_func=DetailView.as_view('detail'))

project_tracker/views/users.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask_login import logout_user, login_required, current_user
from project_tracker.models import Project, Note, User

users = Blueprint('users', __name__, template_folder='templates')

@users.route('/profile')
@login_required
def profile():
    projects = Project.objects(owner=current_user.id)
    return render_template('user/profile.html', projects=projects)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('projects.home'))

project_tracker/templates/_forms.html
{% macro render(form) -%}
<fieldset>
{% for field in form %}
{% if field.type in ['CSRFTokenField', 'HiddenField'] %}
  {{ field() }}
{% else %}
  <div class="form-group {% if field.errors %}error{% endif %}">
    {{ field.label }}
    <div class="input">
      {% if field.name == "body" %}
        {{ field(rows=10, cols=40) }}
      {% else %}
        {{ field() }}
      {% endif %}
      {% if field.errors or field.help_text %}
        <span class="help-inline">
        {% if field.errors %}
          {{ field.errors|join(' ') }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </span>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endfor %}
</fieldset>
{% endmacro %}

project_tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Project Tracker</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <style>.content {padding-top: 80px;} a.brand {color: #FF8C00; }</style>
  </head>

  <body>

    {%- block topbar -%}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <h2>
              <a href="/" class="brand">Track It!</a> <small>a simple Programming Project Tracker </small>
          </h2>
        </div>
        <div class="navbar-collapse">
          <ul class="nav nav-pills navbar-nav navbar-right ">
          {% if current_user.is_authenticated %}
            <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Options
            <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('projects.new') }}">Create a New Project</a></li>
              <li><a href="{{ url_for('projects.home') }}">View All Projects</a></li>
              <li><a href="{{ url_for('users.profile') }}">My Profile</a></li>
              <li><a href="{{ url_for('users.logout') }}">Logout</a></li>              
            </ul>
            </li>
        
          {% else %}
            <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Sign in/Register
            <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              <li><a href="{{ url_for('auth.register') }}">Register</a></li>
            </ul>
           </li>          
          {% endif %}
        </ul>
        </div>
      </div>
    </nav>

    {%- endblock -%}

    <div class="container">
      <div class="content">
        {% block page_header %}{% endblock %}
        {% block content %}{% endblock %}
      </div>
    </div>
      <script
        src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous">          
      </script>
      <!-- Latest compiled JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      {% block js_footer %}
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
      {% endblock %}

  </body>
</html>