project_tracker/views/project.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from flask_mongoengine.wtf import model_form
from project_tracker.models import Project, Note, User

project = Blueprint('projects', __name__, template_folder='templates')


@project.route('/', methods=['POST','GET'])
def home(): 
    projects = Project.objects(public=True)
    # projects = Project.objects.all()
    return render_template('projects/list.html', projects=projects)

@project.route('/new', methods=['POST','GET'])
@login_required
def new():
    project = Project()
    form_project = model_form(Project,  field_args = {'title': {'label': 'Title'},'description': {'label': 'Project Description'},
                                                         'primary_language': {'label':'Primary Programming Language'}, 'tools': {'label':'Other Tools'}, 'slug': {'label':'Unique Project Name'},
                                                         'repo': {'label':'GitHub Repository'}, 'location_url': {'label': 'Hosted Link'},'status': {'label':'Status'}}, 
                                                         exclude=('slug', 'startDate', 'endDate', 'createdDate', 'notes', 'closed', 'week_completed', 'minutes_worked', 'owner'))
    form = form_project(request.form)
    return render_template('projects/create.html', form=form)


@project.route('/create', methods=['POST'])
@login_required
def create():
    public = False    
    if request.form.get(public) == 'y':
        public = True
    else:
        public = False

    project = Project()
    project.title = request.form['title']
    project.public = public
    project.description = request.form['description']
    project.primary_language = request.form.get('primary_language')
    project.tools = request.form.get('tools')
    project.status = request.form['status']
    project.repo = request.form.get('repo')
    project.sources = request.form.get('sources')
   
    project.owner = current_user.id
    project.save()
    _id = project.id

    return render_template('projects/detail.html',project=project)


class DetailView(MethodView):

    form = model_form(Note, field_args={'body' :{'label': 'Write your comment here...'}}, exclude=['publishedDate', 'author'])
    @login_required
    def get_context(self, _id):
        project = Project.objects.get_or_404(id=_id)
        form = self.form(request.form)

        context = {
            "project": project,
            "form": form
        }
        return context
    @login_required
    def get(self, _id):
        context = self.get_context(_id)
        return render_template('projects/detail.html', **context)
    @login_required
    def post(self, _id):
        context = self.get_context(_id)
        form = context.get('form')

        if form.validate():
            note = Note()
            form.populate_obj(note)
            note.author = current_user.id

            project = context.get('project')
            project.notes.append(note)
            project.save()

            return redirect(url_for('projects.detail', _id=_id))
        return render_template('projects/detail.html', **context)
project.add_url_rule('/<_id>/', view_func=DetailView.as_view('detail'))

project_tracker/templates/projects/create.html
{% extends "base.html" %}
{% import "_forms.html" as forms %}


{% block content %}
  <h2>Add new Project</h2>

  <form action="{{ url_for('projects.create') }}" method="post" name="form">
    {{ forms.render(form) }}
    <div class="actions">
      <input type="submit" class="btn btn-primary" value="Save Project">
      <a href="{{ url_for('projects.home') }}" class="btn btn-default">Cancel</a>
    </div>
  </form>
      {% block js_footer %}
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
      {% endblock %}
{% endblock %}

project_tracker/templates/projects/detail.html
{% extends "base.html" %}
{% import '_forms.html' as forms %}

{% block page_header %}
  <div class="page-header">
    <h1>{{ project.title }}</h1>
  </div>
{% endblock %}

{% block content %}
  {% if project.description %}
     <p> {{ project.description }}</p>
  {% endif %}
  <p> <strong> Status: </strong> {{ project.status}} </p>
  <p> <strong> Primary Programming Language: </strong> {{ project.primary_language }} </p>
  {% if project.tools %}
  <p> <strong> Other Tools Used: </strong> </p>
     {% for tool in project.tools.split() %}
       <p> {{ tool }} </p>
     {% endfor %}
  {% endif %}
  {% if project.week_completed %}
    <p> <strong> Week Completed: </strong> {{ project.week_completed }} </p>
  {% endif %}
  {% if project.repo %}
   <p> <strong> Github Repo: </strong> <a href="{{ project.location_url }}"> {{ project.repo|safe() }} </a></p>
  {% endif %}
  {% if project.location_url %}
    <p><strong> Hosted Project: </strong> <a href="{{ project.location_url }}">{{ project.location_url }}</a><p>
  {% endif %}
  {% if project.sources %}
    <p><strong>Resources:</strong> </p>
    {% for source in project.sources.split() %} 
    <p><a href="{{ source }}">{{ source }}</a></p>
    {% endfor %}
  {% endif %}
  <p><strong>Date Created:</strong> {{ project.createdDate.strftime('%Y-%m-%d') }}</p>
  <hr>
  <h2>Comments</h2>
  {% if project.notes %}
    {% for note in project.notes %}
       <p>{{ note.body }}</p>
       {% if note.author %}
       <p><strong>{{ note.author.username }}</strong> <small>on {{ note.publishedDate.strftime('%H:%M %Y-%m-%d') }}</small></p>
       {% endif %}
      {{ note.body }}
    {% endfor %}
  {% else %}
  No Comments yet. Be the First!
  {% endif %}
  <hr>
  
  <form action=".", method="post">
    {{ forms.render(form) }}
    <div class="actions">
      <input type="submit" class="btn btn-primary" value="Post">
    </div>
  </form>
  <hr>
{% endblock %}

project_tracker/templates/projects/list.html
{% extends "base.html" %}

{% block content %}
<h3> Public Projects </h3>
    {% for project in projects %}
      {% if project.status == 'Completed' %}
        <h2>  <a style="color:#008000" href="{{ url_for('projects.detail', _id=project.id) }}">{{ project.title }}</a></h2>
      {% else %}
        <h2>  <a style="color:#FF8C00" href="{{ url_for('projects.detail', _id=project.id) }}">{{ project.title }}</a></h2>
      {% endif %}
      {% if project.owner %}
        <p>By {{ project.owner.username }}</p>
      {% endif %}
        <p> Status: {{ project.status }}</p>
      {% if project.description %}
        <p>{{ project.description|truncate(100) }}</p> 
      {% endif %}

      {% if project.repo %}
        <p><a href="{{ project.repo }}"> GitHub Repo </a></p>
      {% endif %}
      {% if project.location_url %}
        <p><a href="{{ project.location_url }}"> See it Live! </a></p>
      {% endif %}

      <p>
        {{ project.createdDate.strftime('%Y-%m-%d') }} |
        {% with total=project.notes|length %}
            {{ total }} Comments {%- if total > 1 %}s{%- endif -%}
        {% endwith %}
      </p>
    {% endfor %}
{% endblock %}